from ioUtils import getFile
from listUtils import getFlatList
from artistIgnores import getArtistIgnores

class rateYourMusicListCharts:
    def __init__(self):
        self.c_1000_Great_Albums                                                           = ['1000_Great_Albums']
        self.c_1001_Albums_You_Must_Hear                                                   = ['1001_Albums_You_Must_Hear']
        self.c_1001_Albums_You_Must_Hear_Before_You_Die                                    = ['1001_Albums_You_Must_Hear_Before_You_Die']
        self.c_1001_discos_que_debes_escuchar_antes_de_forear                              = ['1001_discos_que_debes_escuchar_antes_de_forear']
        self.c_100_Best_Swedish_Albums                                                     = ['100_Best_Swedish_Albums']
        self.c_100_Favourite_Songs_of_All_Time                                             = ['100_Favourite_Songs_of_All_Time']
        self.c_100_most_mind_bending_life_changing_brain_expanding_records_of_all_time     = ['100_most_mind_bending_life_changing_brain_expanding_records_of_all_time']
        self.c_1500_Songs_From_Under_The_Floorboards                                       = ['1500_Songs_From_Under_The_Floorboards']
        self.c_200_Greatest_Rock_Artists_of_All_Time                                       = ['200_Greatest_Rock_Artists_of_All_Time']
        self.c_200_Russian_Albums                                                          = ['200_Russian_Albums']
        self.c_2010_2019                                                                   = ['2010_2019']
        self.c_3500_Albums_You_Gotta_Listen_To                                             = ['3500_Albums_You_Gotta_Listen_To']
        self.c_3_Favorite_Albums_of_each_year                                              = ['3_Favorite_Albums_of_each_year']
        self.c_500_All_Psychedelic_Albums_Game                                             = ['500_All_Psychedelic_Albums_Game']
        self.c_500_Death_Metal_Recordings_You_Must_Hear_Before_You_Die                     = ['500_Death_Metal_Recordings_You_Must_Hear_Before_You_Die']
        self.c_500_Most_Depressing_Songs_I_Ever_Heard                                      = ['500_Most_Depressing_Songs_I_Ever_Heard']
        self.c_50_Greatest_Hawaii_Albums_of_All_Time                                       = ['50_Greatest_Hawaii_Albums_of_All_Time']
        self.c_70s_80s_Jamaican_Dub                                                        = ['70s_80s_Jamaican_Dub']
        self.c_953_of_My_Favorite_Albums_A_Z                                               = ['953_of_My_Favorite_Albums_A_Z']
        self.c_ALL_JAPAN_The_Greatest_JPN_Albums                                           = ['ALL_JAPAN_The_Greatest_JPN_Albums']
        self.c_Africa_Albums                                                               = ['Africa_Albums']
        self.c_Albums_from_Benelux                                                         = ['Albums_from_Benelux']
        self.c_Albums_from_Canada                                                          = ['Albums_from_Canada']
        self.c_Albums_from_Eastern_Europe                                                  = ['Albums_from_Eastern_Europe']
        self.c_Albums_from_France                                                          = ['Albums_from_France']
        self.c_Albums_from_Germany                                                         = ['Albums_from_Germany']
        self.c_Albums_from_Ireland                                                         = ['Albums_from_Ireland']
        self.c_Albums_from_Italy                                                           = ['Albums_from_Italy']
        self.c_Albums_from_Landlocked_Europe                                               = ['Albums_from_Landlocked_Europe']
        self.c_Albums_from_Oceania                                                         = ['Albums_from_Oceania']
        self.c_Albums_from_Quebec                                                          = ['Albums_from_Quebec']
        self.c_Albums_from_Scandinavia                                                     = ['Albums_from_Scandinavia']
        self.c_Albums_from_Scotland                                                        = ['Albums_from_Scotland']
        self.c_Albums_from_Wales                                                           = ['Albums_from_Wales']
        self.c_Albums_from_the_Caribbean                                                   = ['Albums_from_the_Caribbean']
        self.c_Albums_from_the_Far_East                                                    = ['Albums_from_the_Far_East']
        self.c_Albums_from_the_Iberian_Peninsula                                           = ['Albums_from_the_Iberian_Peninsula']
        self.c_Albums_from_the_Spanish_Americas                                            = ['Albums_from_the_Spanish_Americas']
        self.c_Amazingly_Awful_Album_Art                                                   = ['Amazingly_Awful_Album_Art']
        self.c_An_Artist_from_Every_Region                                                 = ['An_Artist_from_Every_Region']
        self.c_An_Ode_to_the_Death_of_the_80s                                              = ['An_Ode_to_the_Death_of_the_80s']
        self.c_An_Outsider_Guitde_to_Russian_Dance_Music                                   = ['An_Outsider_Guitde_to_Russian_Dance_Music']
        self.c_Around_the_World_of_Traditional_Music_in_80_Records                         = ['Around_the_World_of_Traditional_Music_in_80_Records']
        self.c_Artists_Releases_with_Gujarati_script                                       = ['Artists_Releases_with_Gujarati_script']
        self.c_Artists_Releases_with_Gurmukhi_script                                       = ['Artists_Releases_with_Gurmukhi_script']
        self.c_Artists_Releases_with_Kannada_script                                        = ['Artists_Releases_with_Kannada_script']
        self.c_Artists_Releases_with_Khmer_script                                          = ['Artists_Releases_with_Khmer_script']
        self.c_Artists_Releases_with_Lao_script                                            = ['Artists_Releases_with_Lao_script']
        self.c_Artists_Releases_with_Malayalam_script                                      = ['Artists_Releases_with_Malayalam_script']
        self.c_Artists_Releases_with_NKo_script                                            = ['Artists_Releases_with_NKo_script']
        self.c_Artists_Releases_with_Oriya_script                                          = ['Artists_Releases_with_Oriya_script']
        self.c_Artists_Releases_with_Syriac_script                                         = ['Artists_Releases_with_Syriac_script']
        self.c_Artists_Releases_with_Telugu_script                                         = ['Artists_Releases_with_Telugu_script']
        self.c_Artists_Releases_with_Tibetan_script                                        = ['Artists_Releases_with_Tibetan_script']
        self.c_Artists_Releases_with_Tifinagh_script                                       = ['Artists_Releases_with_Tifinagh_script']
        self.c_Artists_with_Arabic_script                                                  = ['Artists_with_Arabic_script']
        self.c_Artists_with_Armenian_script                                                = ['Artists_with_Armenian_script']
        self.c_Artists_with_Bengali_script                                                 = ['Artists_with_Bengali_script']
        self.c_Artists_with_Burmese_script                                                 = ['Artists_with_Burmese_script']
        self.c_Artists_with_Devanagari_script                                              = ['Artists_with_Devanagari_script']
        self.c_Artists_with_Geez_script                                                    = ['Artists_with_Geez_script']
        self.c_Artists_with_Greek_script                                                   = ['Artists_with_Greek_script']
        self.c_Artists_with_Hangul_script                                                  = ['Artists_with_Hangul_script']
        self.c_Artists_with_Hebrew_script                                                  = ['Artists_with_Hebrew_script']
        self.c_Artists_with_Sinhala_script                                                 = ['Artists_with_Sinhala_script']
        self.c_Artists_with_Tamil_script                                                   = ['Artists_with_Tamil_script']
        self.c_Artists_with_Thai_script                                                    = ['Artists_with_Thai_script']
        self.c_Awful_Ass_Album_Covers                                                      = ['Awful_Ass_Album_Covers']
        self.c_Best_360_R_B_Albums                                                         = ['Best_360_R_B_Albums']
        self.c_Best_Albums_Of_All_Time                                                     = ['Best_Albums_Of_All_Time']
        self.c_Best_Albums_of_Reggaeton_of_All_Time                                        = ['Best_Albums_of_Reggaeton_of_All_Time']
        self.c_Best_Female_Voices                                                          = ['Best_Female_Voices']
        self.c_Best_of_Jazz_Improv_1970s_2010s_                                            = ['Best_of_Jazz_Improv_1970s_2010s_']
        self.c_Best_of_the_1970s                                                           = ['Best_of_the_1970s']
        self.c_Best_of_the_1980s                                                           = ['Best_of_the_1980s']
        self.c_Billboard_charts_1990s                                                      = ['Billboard_charts_1990s']
        self.c_Black_White                                                                 = ['Black_White']
        self.c_Blood_Pumps_1500_Favorite_Albums                                            = ['Blood_Pumps_1500_Favorite_Albums']
        self.c_Blow_Up_Magazines_600_essential_albums                                      = ['Blow_Up_Magazines_600_essential_albums']
        self.c_Brazil                                                                      = ['Brazil']
        self.c_CITY_LIFE_ESCAPE                                                            = ['CITY_LIFE_ESCAPE']
        self.c_COUNTRY_STRONG                                                              = ['COUNTRY_STRONG']
        self.c_Canada_in_the_1980s                                                         = ['Canada_in_the_1980s']
        self.c_Country_Rock_Colossus                                                       = ['Country_Rock_Colossus']
        self.c_DJ_Mixes                                                                    = ['DJ_Mixes']
        self.c_Danish_Artists                                                              = ['Danish_Artists']
        self.c_Dark_Ambient_Essentials                                                     = ['Dark_Ambient_Essentials']
        self.c_EMI_Nigeria_45s                                                             = ['EMI_Nigeria_45s']
        self.c_Eastern_Europe_DIY_Tapes_1978_89                                            = ['Eastern_Europe_DIY_Tapes_1978_89']
        self.c_Emo_Rap                                                                     = ['Emo_Rap']
        self.c_Ethereal_Voices_in_Metal                                                    = ['Ethereal_Voices_in_Metal']
        self.c_Every_Charting_Single_in_the_UK                                             = ['Every_Charting_Single_in_the_UK']
        self.c_Favorite_Albums_2010_2019                                                   = ['Favorite_Albums_2010_2019']
        self.c_Favorite_Anthologies_Albums                                                 = ['Favorite_Anthologies_Albums']
        self.c_Favorite_Chinese_Albums                                                     = ['Favorite_Chinese_Albums']
        self.c_Favorite_Danish_Albums                                                      = ['Favorite_Danish_Albums']
        self.c_Favorite_Pop_Albums                                                         = ['Favorite_Pop_Albums']
        self.c_Favorite_Russian_Albums                                                     = ['Favorite_Russian_Albums']
        self.c_Foreign_Language_Albums_in_the_RYM_all_time                                 = ['Foreign_Language_Albums_in_the_RYM_all_time']
        self.c_Forever_Young_2500_Best_Songs                                               = ['Forever_Young_2500_Best_Songs']
        self.c_Funk_Albums_from_the_United_States_and_England                              = ['Funk_Albums_from_the_United_States_and_England']
        self.c_Futuristic_music                                                            = ['Futuristic_music']
        self.c_Gentle_Dads                                                                 = ['Gentle_Dads']
        self.c_Good_Ass_Album_Covers                                                       = ['Good_Ass_Album_Covers']
        self.c_Grammy_Album_of_the_Year                                                    = ['Grammy_Album_of_the_Year']
        self.c_Great_Albums_Made_by_Artists_over_60_years_old                              = ['Great_Albums_Made_by_Artists_over_60_years_old']
        self.c_Great_Albums_Made_by_Artists_under_20_years_old                             = ['Great_Albums_Made_by_Artists_under_20_years_old']
        self.c_Great_Belgian_Artists                                                       = ['Great_Belgian_Artists']
        self.c_Great_obscure_lesser_known_albums                                           = ['Great_obscure_lesser_known_albums']
        self.c_Greatest_Rappers_of_All_Time                                                = ['Greatest_Rappers_of_All_Time']
        self.c_Greek_Artists                                                               = ['Greek_Artists']
        self.c_Greek_Artists_Classical_Orchestral_Jazz_Ethnic_Byzantine_and_multiple_genre_composers = ['Greek_Artists_Classical_Orchestral_Jazz_Ethnic_Byzantine_and_multiple_genre_composers']
        self.c_Guide_To_Indie_Twee_Pop                                                     = ['Guide_To_Indie_Twee_Pop']
        self.c_Hazy_Memory_Nocturnal_Version                                               = ['Hazy_Memory_Nocturnal_Version']
        self.c_Helio_Reviews_the_Singles                                                   = ['Helio_Reviews_the_Singles']
        self.c_Hip_Hop_Artists_for_Me_to_Check_Out                                         = ['Hip_Hop_Artists_for_Me_to_Check_Out']
        self.c_Hip_Hop_Greatest_Albums_of_All_Time                                         = ['Hip_Hop_Greatest_Albums_of_All_Time']
        self.c_Hip_Hop_in_the_2010s_An_Essential_Chronology                                = ['Hip_Hop_in_the_2010s_An_Essential_Chronology']
        self.c_J_Pop_and_K_Pop_Party                                                       = ['J_Pop_and_K_Pop_Party']
        self.c_Japanese_Albums_That_I_Like                                                 = ['Japanese_Albums_That_I_Like']
        self.c_Jazz_Core_Collection                                                        = ['Jazz_Core_Collection']
        self.c_Jazz_and_other_Jazz_styles_from_Africa                                      = ['Jazz_and_other_Jazz_styles_from_Africa']
        self.c_Jazzcore_Punk_Jazz_Brutal_Jazz_etc_                                         = ['Jazzcore_Punk_Jazz_Brutal_Jazz_etc_']
        self.c_Lets_listen_to_Canadian_progressive_music                                   = ['Lets_listen_to_Canadian_progressive_music']
        self.c_Most_commented_on_comment_boxes                                             = ['Most_commented_on_comment_boxes']
        self.c_Music_to_commit_suicide_to                                                  = ['Music_to_commit_suicide_to']
        self.c_My_100_Favourite_Singles_of_the_1990s                                       = ['My_100_Favourite_Singles_of_the_1990s']
        self.c_My_300_Favourite_Albums_Ranked                                              = ['My_300_Favourite_Albums_Ranked']
        self.c_My_300_favorite_Albums                                                      = ['My_300_favorite_Albums']
        self.c_My_75_Favourite_Singles_of_the_2000s                                        = ['My_75_Favourite_Singles_of_the_2000s']
        self.c_My_Best_Hip_Hop_Producers_Of_All_Time                                       = ['My_Best_Hip_Hop_Producers_Of_All_Time']
        self.c_My_Top_1000_Favorite_Hip_Hop_Albums                                         = ['My_Top_1000_Favorite_Hip_Hop_Albums']
        self.c_My_Top_100_Swedish_Albums                                                   = ['My_Top_100_Swedish_Albums']
        self.c_My_Top_2500_Bands_of_all_time                                               = ['My_Top_2500_Bands_of_all_time']
        self.c_My_Top_500_Songs_of_All_Time                                                = ['My_Top_500_Songs_of_All_Time']
        self.c_My_favorite_Album_Covers_of_SIX_different_types                             = ['My_favorite_Album_Covers_of_SIX_different_types']
        self.c_My_number_1_hits                                                            = ['My_number_1_hits']
        self.c_My_top_50_Britpop_songs_                                                    = ['My_top_50_Britpop_songs_']
        self.c_Nightwalking_Music                                                          = ['Nightwalking_Music']
        self.c_Obscurities                                                                 = ['Obscurities']
        self.c_POPTIMISM_Boy_Bands_Girl_Groups_Pop_Rock_Electropop_90s_onward_Dance_Pop_Latin_Pop_K_Pop_J_Pop_Teen_Pop = ['POPTIMISM_Boy_Bands_Girl_Groups_Pop_Rock_Electropop_90s_onward_Dance_Pop_Latin_Pop_K_Pop_J_Pop_Teen_Pop']
        self.c_Personal_250_Korean_Albums                                                  = ['Personal_250_Korean_Albums']
        self.c_Post_club_deconstructed_club_Albums_EPs_and_compilations                    = ['Post_club_deconstructed_club_Albums_EPs_and_compilations']
        self.c_Prolific_Outsiders_and_Weirdos                                              = ['Prolific_Outsiders_and_Weirdos']
        self.c_Psychedelic_60s                                                             = ['Psychedelic_60s']
        self.c_Ranking_Albums_of_2016                                                      = ['Ranking_Albums_of_2016']
        self.c_Recommended_Dance_Singles_EP                                                = ['Recommended_Dance_Singles_EP']
        self.c_Releases_with_Armenian_script                                               = ['Releases_with_Armenian_script']
        self.c_Releases_with_Devanagari_script                                             = ['Releases_with_Devanagari_script']
        self.c_Releases_with_Hangul_script                                                 = ['Releases_with_Hangul_script']
        self.c_Rolling_Stone_Japans_100_Greatest_Japanese_Rock_Albums_of_All_Time          = ['Rolling_Stone_Japans_100_Greatest_Japanese_Rock_Albums_of_All_Time']
        self.c_Russian_Post_Punk                                                           = ['Russian_Post_Punk']
        self.c_Scandinavian_Rock                                                           = ['Scandinavian_Rock']
        self.c_Serpentine_Gallery_50_Of_The_Very_Best_Post_Punk_Albums                     = ['Serpentine_Gallery_50_Of_The_Very_Best_Post_Punk_Albums']
        self.c_Short_Dogs_In_The_House_The_Shortest_Albums_Ever                            = ['Short_Dogs_In_The_House_The_Shortest_Albums_Ever']
        self.c_Song_of_the_day                                                             = ['Song_of_the_day']
        self.c_Strongest_Chinese_Albums_in_History                                         = ['Strongest_Chinese_Albums_in_History']
        self.c_Summer_song_playlist                                                        = ['Summer_song_playlist']
        self.c_TOP_100_SONGWRITERS                                                         = ['TOP_100_SONGWRITERS']
        self.c_Tapeaholics_Anonymous                                                       = ['Tapeaholics_Anonymous']
        self.c_Thailand_Luk_Thung_Molam                                                    = ['Thailand_Luk_Thung_Molam']
        self.c_The_Best_500_Albums_Of_The_20th_Century                                     = ['The_Best_500_Albums_Of_The_20th_Century']
        self.c_The_Best_Album_in_Every_Genre_Ive_Heard                                     = ['The_Best_Album_in_Every_Genre_Ive_Heard']
        self.c_The_Top_100_Albums_of_1980s                                                 = ['The_Top_100_Albums_of_1980s']
        self.c_The_Top_125_Singles_of_1997                                                 = ['The_Top_125_Singles_of_1997']
        self.c_The_Wires_150_Sonic_Essentials_and_Aural_Obscurities                        = ['The_Wires_150_Sonic_Essentials_and_Aural_Obscurities']
        self.c_The_best_songs_by_all_female_rock_bands                                     = ['The_best_songs_by_all_female_rock_bands']
        self.c_The_most_melancholic_albums_ever                                            = ['The_most_melancholic_albums_ever']
        self.c_These_1_840_K_Pop_Albums_Are_the_Best_Maybe                                 = ['These_1_840_K_Pop_Albums_Are_the_Best_Maybe']
        self.c_Top_1000_tracks_of_all_time                                                 = ['Top_1000_tracks_of_all_time']
        self.c_Top_100_Alt_Country_Albums_of_All_Time                                      = ['Top_100_Alt_Country_Albums_of_All_Time']
        self.c_Top_100_Favorite_Hip_Hop_Albums_of_All_Time                                 = ['Top_100_Favorite_Hip_Hop_Albums_of_All_Time']
        self.c_Top_100_Japanese_Albums                                                     = ['Top_100_Japanese_Albums']
        self.c_Top_1200_Singles_of_the_90s                                                 = ['Top_1200_Singles_of_the_90s']
        self.c_Top_200_Worst_Artists_v2                                                    = ['Top_200_Worst_Artists_v2']
        self.c_Top_250_Reggae_Albums_According_to_RYMs_Heavy_Reggae_Heads_                 = ['Top_250_Reggae_Albums_According_to_RYMs_Heavy_Reggae_Heads_']
        self.c_Top_500_Best_Albums_Ever_Made                                               = ['Top_500_Best_Albums_Ever_Made']
        self.c_Top_501_Favorite_Albums                                                     = ['Top_501_Favorite_Albums']
        self.c_Top_50_albums_by_nordic_scandinavian_artists                                = ['Top_50_albums_by_nordic_scandinavian_artists']
        self.c_Top_Artists_Chart                                                           = ['Top_Artists_Chart']
        self.c_Trap_releases_I_like                                                        = ['Trap_releases_I_like']
        self.c_UK_Singles_Chart_Every_artist_that_reached_1                                = ['UK_Singles_Chart_Every_artist_that_reached_1']
        self.c_Ultimate_NonPop                                                             = ['Ultimate_NonPop']
        self.c_Ultimate_Songs_of_1990                                                      = ['Ultimate_Songs_of_1990']
        self.c_Upbeat_2000s_Pop                                                            = ['Upbeat_2000s_Pop']
        self.c_Upbeat_2020s_Pop                                                            = ['Upbeat_2020s_Pop']
        self.c_Upbeat_70s_Pop                                                              = ['Upbeat_70s_Pop']
        self.c_Upbeat_80s_Pop                                                              = ['Upbeat_80s_Pop']
        self.c_Upbeat_90s_Pop                                                              = ['Upbeat_90s_Pop']
        self.c_Voice_is_an_instrument_Extended_vocal_vocabulary                            = ['Voice_is_an_instrument_Extended_vocal_vocabulary']
        self.c_WOEBOTs_The_100_Greatest_Records_Ever                                       = ['WOEBOTs_The_100_Greatest_Records_Ever']
        self.c_Who_ruled_the_80s_The_200_biggest_artists_of_the_decade_in_the_USA_         = ['Who_ruled_the_80s_The_200_biggest_artists_of_the_decade_in_the_USA_']
        self.c_XPNs_2014_88_Worst_Songs_Of_All_Time                                        = ['XPNs_2014_88_Worst_Songs_Of_All_Time']
        self.c_You_Make_Me_Feel_Like_A_Tyrannosaurus_Rex_Dinosaur_Cover_Art                = ['You_Make_Me_Feel_Like_A_Tyrannosaurus_Rex_Dinosaur_Cover_Art']
        self.c_all_the_k_Pop                                                               = ['all_the_k_Pop']
        self.c_contemporary_r_b_that_goes_against_the_grain                                = ['contemporary_r_b_that_goes_against_the_grain']
        self.c_r_b_for_the_sleepless_deep_r_b_                                             = ['r_b_for_the_sleepless_deep_r_b_']
        self.c_rym                                                                         = ['rym']
        self.c_s_a_d                                                                       = ['s_a_d']
        self.c_songs_that_youtube_are_manipulating_me_into_listening_to                    = ['songs_that_youtube_are_manipulating_me_into_listening_to']
        self.c_terrorize_the_jam_like_troops_in_Pakistan                                   = ['terrorize_the_jam_like_troops_in_Pakistan']
        self.c_thats_the_way_love_is_200_deep_house_selection                              = ['thats_the_way_love_is_200_deep_house_selection']
        self.c_top_500_songs                                                               = ['top_500_songs']
        self.c_underground_new_wave_from_USA                                               = ['underground_new_wave_from_USA']
        self.c_untitled_folder                                                             = ['untitled_folder']


        self.chartNames = self.__dict__.keys()


        self.chartRanks = {}
        ######### Singles - Best #########
        ######### Singles - Worst #########
        ######### Albums - Best #########
        ######### Albums - Diverse #########
        ######### Albums - Esoteric #########
        ######### Albums - Worst #########
        ######### Mixes - Best #########
        ######### Mixes - Worst #########
        ######### Albums - Yearly #########
        ######### Singles - BestYearly #########
        ######### Singles - WorstYearly #########
        ######### Titles #########
        self.chartRanks[0] = ['c_1000_Great_Albums', 'c_1001_Albums_You_Must_Hear', 'c_1001_Albums_You_Must_Hear_Before_You_Die', 'c_100_Best_Swedish_Albums', 'c_100_Favourite_Songs_of_All_Time', 'c_1500_Songs_From_Under_The_Floorboards']
        self.chartRanks[1] = ['c_200_Russian_Albums', 'c_3500_Albums_You_Gotta_Listen_To', 'c_3_Favorite_Albums_of_each_year', 'c_500_All_Psychedelic_Albums_Game', 'c_500_Most_Depressing_Songs_I_Ever_Heard', 'c_50_Greatest_Hawaii_Albums_of_All_Time']
        self.chartRanks[2] = ['c_953_of_My_Favorite_Albums_A_Z', 'c_ALL_JAPAN_The_Greatest_JPN_Albums', 'c_Africa_Albums', 'c_Albums_from_Benelux', 'c_Albums_from_Canada', 'c_Albums_from_Eastern_Europe']
        self.chartRanks[3] = ['c_Albums_from_France', 'c_Albums_from_Germany', 'c_Albums_from_Ireland', 'c_Albums_from_Italy', 'c_Albums_from_Landlocked_Europe', 'c_Albums_from_Oceania']
        self.chartRanks[4] = ['c_Albums_from_Quebec', 'c_Albums_from_Scandinavia', 'c_Albums_from_Scotland', 'c_Albums_from_Wales', 'c_Albums_from_the_Caribbean', 'c_Albums_from_the_Far_East']
        self.chartRanks[5] = ['c_Albums_from_the_Iberian_Peninsula', 'c_Albums_from_the_Spanish_Americas', 'c_Amazingly_Awful_Album_Art', 'c_Awful_Ass_Album_Covers', 'c_Best_360_R_B_Albums', 'c_Best_Albums_Of_All_Time']
        self.chartRanks[6] = ['c_Best_Albums_of_Reggaeton_of_All_Time', 'c_Blood_Pumps_1500_Favorite_Albums', 'c_Favorite_Albums_2010_2019', 'c_Favorite_Anthologies_Albums', 'c_Favorite_Chinese_Albums', 'c_Favorite_Danish_Albums']
        self.chartRanks[7] = ['c_Favorite_Pop_Albums', 'c_Favorite_Russian_Albums', 'c_Foreign_Language_Albums_in_the_RYM_all_time', 'c_Forever_Young_2500_Best_Songs', 'c_Funk_Albums_from_the_United_States_and_England', 'c_Good_Ass_Album_Covers']
        self.chartRanks[8] = ['c_Grammy_Album_of_the_Year', 'c_Great_Albums_Made_by_Artists_over_60_years_old', 'c_Great_Albums_Made_by_Artists_under_20_years_old', 'c_Hip_Hop_Greatest_Albums_of_All_Time', 'c_Japanese_Albums_That_I_Like', 'c_My_300_Favourite_Albums_Ranked']
        self.chartRanks[9] = ['c_My_300_favorite_Albums', 'c_My_Top_1000_Favorite_Hip_Hop_Albums', 'c_My_Top_100_Swedish_Albums', 'c_My_Top_500_Songs_of_All_Time', 'c_My_favorite_Album_Covers_of_SIX_different_types', 'c_Personal_250_Korean_Albums']
        self.chartRanks[10] = ['c_Post_club_deconstructed_club_Albums_EPs_and_compilations', 'c_Ranking_Albums_of_2016', 'c_Rolling_Stone_Japans_100_Greatest_Japanese_Rock_Albums_of_All_Time', 'c_Serpentine_Gallery_50_Of_The_Very_Best_Post_Punk_Albums', 'c_Short_Dogs_In_The_House_The_Shortest_Albums_Ever', 'c_Song_of_the_day']
        self.chartRanks[11] = ['c_Strongest_Chinese_Albums_in_History', 'c_The_Best_500_Albums_Of_The_20th_Century', 'c_The_Best_Album_in_Every_Genre_Ive_Heard', 'c_The_Top_100_Albums_of_1980s', 'c_These_1_840_K_Pop_Albums_Are_the_Best_Maybe', 'c_Top_100_Alt_Country_Albums_of_All_Time']
        self.chartRanks[12] = ['c_Top_100_Favorite_Hip_Hop_Albums_of_All_Time', 'c_Top_100_Japanese_Albums', 'c_Top_250_Reggae_Albums_According_to_RYMs_Heavy_Reggae_Heads_', 'c_Top_500_Best_Albums_Ever_Made', 'c_Top_501_Favorite_Albums', 'c_Ultimate_Songs_of_1990']
        self.chartRanks[13] = ['c_XPNs_2014_88_Worst_Songs_Of_All_Time']
        ######### Artists #########
        self.chartRanks[14] = ['c_200_Greatest_Rock_Artists_of_All_Time', 'c_An_Artist_from_Every_Region', 'c_Danish_Artists', 'c_Great_Belgian_Artists', 'c_Greek_Artists', 'c_Greek_Artists_Classical_Orchestral_Jazz_Ethnic_Byzantine_and_multiple_genre_composers']
        self.chartRanks[15] = ['c_Hip_Hop_Artists_for_Me_to_Check_Out', 'c_Top_200_Worst_Artists_v2', 'c_Top_Artists_Chart']
        ######### Script #########
        self.chartRanks[16] = ['c_Artists_Releases_with_Gujarati_script', 'c_Artists_Releases_with_Gurmukhi_script']
        self.chartRanks[17] = ['c_Artists_Releases_with_Kannada_script', 'c_Artists_Releases_with_Khmer_script']
        self.chartRanks[18] = ['c_Artists_Releases_with_Lao_script', 'c_Artists_Releases_with_Malayalam_script']
        self.chartRanks[19] = ['c_Artists_Releases_with_NKo_script', 'c_Artists_Releases_with_Oriya_script']
        self.chartRanks[20] = ['c_Artists_Releases_with_Syriac_script', 'c_Artists_Releases_with_Telugu_script']
        self.chartRanks[21] = ['c_Artists_Releases_with_Tibetan_script', 'c_Artists_Releases_with_Tifinagh_script']
        self.chartRanks[22] = ['c_Artists_with_Arabic_script', 'c_Artists_with_Armenian_script']
        self.chartRanks[23] = ['c_Artists_with_Bengali_script', 'c_Artists_with_Burmese_script']
        self.chartRanks[24] = ['c_Artists_with_Devanagari_script', 'c_Artists_with_Geez_script']
        self.chartRanks[25] = ['c_Artists_with_Greek_script', 'c_Artists_with_Hangul_script']
        self.chartRanks[26] = ['c_Artists_with_Hebrew_script', 'c_Artists_with_Sinhala_script']
        self.chartRanks[27] = ['c_Artists_with_Tamil_script', 'c_Artists_with_Thai_script']
        self.chartRanks[28] = ['c_Releases_with_Armenian_script', 'c_Releases_with_Devanagari_script']
        self.chartRanks[29] = ['c_Releases_with_Hangul_script']
        ######### Other #########
        self.chartRanks[30] = ['c_1001_discos_que_debes_escuchar_antes_de_forear', 'c_100_most_mind_bending_life_changing_brain_expanding_records_of_all_time', 'c_2010_2019', 'c_500_Death_Metal_Recordings_You_Must_Hear_Before_You_Die', 'c_70s_80s_Jamaican_Dub', 'c_An_Ode_to_the_Death_of_the_80s']
        self.chartRanks[31] = ['c_An_Outsider_Guitde_to_Russian_Dance_Music', 'c_Around_the_World_of_Traditional_Music_in_80_Records', 'c_Best_Female_Voices', 'c_Best_of_Jazz_Improv_1970s_2010s_', 'c_Best_of_the_1970s', 'c_Best_of_the_1980s']
        self.chartRanks[32] = ['c_Billboard_charts_1990s', 'c_Black_White', 'c_Blow_Up_Magazines_600_essential_albums', 'c_Brazil', 'c_CITY_LIFE_ESCAPE', 'c_COUNTRY_STRONG']
        self.chartRanks[33] = ['c_Canada_in_the_1980s', 'c_Country_Rock_Colossus', 'c_DJ_Mixes', 'c_Dark_Ambient_Essentials', 'c_EMI_Nigeria_45s', 'c_Eastern_Europe_DIY_Tapes_1978_89']
        self.chartRanks[34] = ['c_Emo_Rap', 'c_Ethereal_Voices_in_Metal', 'c_Every_Charting_Single_in_the_UK', 'c_Futuristic_music', 'c_Gentle_Dads', 'c_Great_obscure_lesser_known_albums']
        self.chartRanks[35] = ['c_Greatest_Rappers_of_All_Time', 'c_Guide_To_Indie_Twee_Pop', 'c_Hazy_Memory_Nocturnal_Version', 'c_Helio_Reviews_the_Singles', 'c_Hip_Hop_in_the_2010s_An_Essential_Chronology', 'c_J_Pop_and_K_Pop_Party']
        self.chartRanks[36] = ['c_Jazz_Core_Collection', 'c_Jazz_and_other_Jazz_styles_from_Africa', 'c_Jazzcore_Punk_Jazz_Brutal_Jazz_etc_', 'c_Lets_listen_to_Canadian_progressive_music', 'c_Most_commented_on_comment_boxes', 'c_Music_to_commit_suicide_to']
        self.chartRanks[37] = ['c_My_100_Favourite_Singles_of_the_1990s', 'c_My_75_Favourite_Singles_of_the_2000s', 'c_My_Best_Hip_Hop_Producers_Of_All_Time', 'c_My_Top_2500_Bands_of_all_time', 'c_My_number_1_hits', 'c_My_top_50_Britpop_songs_']
        self.chartRanks[38] = ['c_Nightwalking_Music', 'c_Obscurities', 'c_POPTIMISM_Boy_Bands_Girl_Groups_Pop_Rock_Electropop_90s_onward_Dance_Pop_Latin_Pop_K_Pop_J_Pop_Teen_Pop', 'c_Prolific_Outsiders_and_Weirdos', 'c_Psychedelic_60s', 'c_Recommended_Dance_Singles_EP']
        self.chartRanks[39] = ['c_Russian_Post_Punk', 'c_Scandinavian_Rock', 'c_Summer_song_playlist', 'c_TOP_100_SONGWRITERS', 'c_Tapeaholics_Anonymous', 'c_Thailand_Luk_Thung_Molam']
        self.chartRanks[40] = ['c_The_Top_125_Singles_of_1997', 'c_The_Wires_150_Sonic_Essentials_and_Aural_Obscurities', 'c_The_best_songs_by_all_female_rock_bands', 'c_The_most_melancholic_albums_ever', 'c_Top_1000_tracks_of_all_time', 'c_Top_1200_Singles_of_the_90s']
        self.chartRanks[41] = ['c_Top_50_albums_by_nordic_scandinavian_artists', 'c_Trap_releases_I_like', 'c_UK_Singles_Chart_Every_artist_that_reached_1', 'c_Ultimate_NonPop', 'c_Upbeat_2000s_Pop', 'c_Upbeat_2020s_Pop']
        self.chartRanks[42] = ['c_Upbeat_70s_Pop', 'c_Upbeat_80s_Pop', 'c_Upbeat_90s_Pop', 'c_Voice_is_an_instrument_Extended_vocal_vocabulary', 'c_WOEBOTs_The_100_Greatest_Records_Ever', 'c_Who_ruled_the_80s_The_200_biggest_artists_of_the_decade_in_the_USA_']
        self.chartRanks[43] = ['c_You_Make_Me_Feel_Like_A_Tyrannosaurus_Rex_Dinosaur_Cover_Art', 'c_all_the_k_Pop', 'c_contemporary_r_b_that_goes_against_the_grain', 'c_r_b_for_the_sleepless_deep_r_b_', 'c_rym', 'c_s_a_d']
        self.chartRanks[44] = ['c_songs_that_youtube_are_manipulating_me_into_listening_to', 'c_terrorize_the_jam_like_troops_in_Pakistan', 'c_thats_the_way_love_is_200_deep_house_selection', 'c_top_500_songs', 'c_underground_new_wave_from_USA', 'c_untitled_folder']
        ######### Releases - Best #########
        ######### Releases - Worst #########  
        
        
    def getChartsByRank(self, rank):
        print("Using Charts For Rank {0}".format(rank))
        categories = self.chartRanks[rank]
        print("    Categories: {0}".format(categories))
        charts = []
        for chart in categories:
            print("\tChart: {0}".format(chart))
            charts += self.getCharts(chart)
        print("Using {0} Charts For Rank {1}".format(len(charts), rank))
        return charts
        
    def getCharts(self, name=None):        
        charts = []
        if name is None:
            print("  Getting All Charts")
            for chart in self.chartNames:
                charts += self.__dict__[chart]
        else:
            #print("  Getting Chart For [{0}]".format(name))
            name = name.replace("-", "_")
            #print("name = {0}".format(name))
            if name in self.__dict__.keys():
                chartList = self.__dict__[name]
                if isinstance(chartList[0], list):
                    charts += getFlatList(chartList)
                else:
                    charts += chartList
        if len(charts) == 0:
            raise ValueError("Could not find any charts: {0}".format(self.__dict__.keys()))
        print("  Using {0} Charts".format(len(charts)))
        return charts
